### ISSUE TITLE
Pictures missing for Skywallet Manuals

### ISSUE THREAD

**Issue by sreekumar13** [skycoin/hardware-wallet-manual#29]
1. Unofficial Firmware Detected
2. Images showing the random nature while entering the words in a Seed, when the user is trying to restore an existing Wallet, at least 2 pictures will be needed to show the random nature.
3. Image showing the Skywallet asking to enter a random word during the Wallet restoration process.
4. Screenshot of the receiving address for the address provided in the Skywallet image which was shared.
5. Screenshot of the warning message displayed when the firmware is outdated.
6. Another screenshot of the same warning message if it was ignored by the user on the Hardware Wallet window.
7. A screenshot of the Desktop Wallet window with no Wallets configured, in that case the Hardware Wallet button will not be available instead " Using a Hardware Wallet" will be available. @jdknives

**Comment by jdknives** [comment]
1. Yes. 
2. Maybe fine if we go without it.
3. Yes. 
4. Think it is not different from the screen for confirming which address to send to. But can check again.
5. Yes
6. Not sure what you mean. Please elaborate.
7. You should be  able to get that on your PC.

@sreekumar13
